### ISSUE TITLE
The run_iozone.py lacks the proper iozone binary to execute

### ISSUE THREAD

**Issue by ruda** [avocado-framework/avocado-virt-tests#8]
The current condition of `run_iozone.py` fails to execute the test, due the `iozone` binary is not available in the jeos image. Also, I think iozone has a non-free license [http://www.iozone.org/docs/Iozone_License.txt], that probably disallow us to bundle it with the test or include it in the jeos image.

My effort was then to instruct the test to download the sources, compile and run the test. But the jeos image started by avocado lacks sufficient memory to install gcc and it fails.

```diff
diff --git a/qemu/run_iozone.py b/qemu/run_iozone.py
index e9c43a6..5f27b8e 100644
--- a/qemu/run_iozone.py
+++ b/qemu/run_iozone.py
@@ -23,6 +23,8 @@ class RunIOZoneTest(test.VirtTest):
     def action(self):
         self.vm.power_on()
         self.vm.login_remote()
+        self.vm.remote.run('curl -O http://www.iozone.org/src/current/iozone3_430.tar')
+        self.vm.remote.run('yum install -y gcc')
         self.whiteboard = self.vm.remote.run('iozone -a').stdout
 
     def cleanup(self):
```

**Comment by adereis** [comment]
The test requires an image with iozone. Trying to run it with an image that doesn't have it should return an error. This is covered in the multiplex file, where special parameters are overriden:

```
plugins:
    virt:
        guest:
            image_path: "/home/user/avocado/data/images/distro-with-iozone.qcow2"
            user: "john_doe"
            password: "pass1"
```

But this is not well documented. Documentation is in our to-do list, tracked by this trello card: https://trello.com/c/ujbc5S8a/269-mux-documentation-about-avocado-params-namespaces
